server:
  port: 8001
spring:
  application:
    name: microservicecloud-dept
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
eureka:
  instance:
    instance-id: micraservicecloud8001Hysrix
    prefer-ip-address: true
  client:
    service-url:
       defaultZone: http://Eurekademo1:7001/eureka,http://Eurekademo2:7002/eureka
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.comuii
  build.artifactId: $project.artifactId$
  build.version: $project.version$