server:
  port: 7001
eureka:
  instance:
    hostname: Eurekademo1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://Eurekademo2:7002/eureka/
